version: "3"

services:
  front:
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  back:
    build:
      context: back
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8080"

  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres