version: "3"

services:
  front:
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  back:
    build:
      context: back
      dockerfile: Dockerfile
    ports:
      - "8081:8000"