// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type NewTodo struct {
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	DueDate     time.Time `json:"dueDate"`
}

type Todo struct {
	UserID      string     `json:"userId"`
	Title       string     `json:"title"`
	Description *string    `json:"description"`
	DueDate     time.Time  `json:"dueDate"`
	Done        bool       `json:"done"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   *time.Time `json:"updatedAt"`
}
